In [52]:
import numpy as np

In [53]:
#Creation


In [3]:
data = np.random.rand(2,3,4)
zeros=np.zeros((2,2,2))
full=np.full((2,2,2),7)
ones=np.ones(2,2,2)

In [4]:
data

array([[[0.6226004 , 0.63728812, 0.99969225, 0.23295686],
        [0.42812099, 0.12910182, 0.91996601, 0.80012917],
        [0.93121527, 0.00516949, 0.4965076 , 0.20494078]],

       [[0.13764665, 0.50697818, 0.87629618, 0.56344218],
        [0.21418864, 0.78503022, 0.67751233, 0.28541962],
        [0.08911955, 0.20271771, 0.00100353, 0.74606217]]])

In [6]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
data.shape

(2, 3, 4)

In [10]:
data.size

24

In [11]:
data.dtype

dtype('float64')

In [12]:
data[-1]

array([[0.13764665, 0.50697818, 0.87629618, 0.56344218],
       [0.21418864, 0.78503022, 0.67751233, 0.28541962],
       [0.08911955, 0.20271771, 0.00100353, 0.74606217]])

In [13]:
list1= np.random.rand(10)
list2= np.random.rand(10)

In [14]:
list1

array([0.11285768, 0.64131921, 0.24755843, 0.89466479, 0.47655644,
       0.55529082, 0.08851136, 0.77015281, 0.04312901, 0.10984796])

In [15]:
list2

array([0.27513897, 0.63126439, 0.89253614, 0.69176631, 0.65415467,
       0.18748679, 0.15983017, 0.11989042, 0.79841853, 0.68613144])

In [17]:
#Basic Math

add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mul = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [18]:
add

array([0.38799666, 1.27258361, 1.14009457, 1.5864311 , 1.13071111,
       0.74277762, 0.24834153, 0.89004324, 0.84154754, 0.79597939])

In [19]:
sub

array([-0.16228129,  0.01005482, -0.6449777 ,  0.20289848, -0.17759823,
        0.36780403, -0.07131881,  0.65026239, -0.75528952, -0.57628348])

In [20]:
div

array([0.41018428, 1.01592806, 0.27736517, 1.29330494, 0.72850728,
       2.96175969, 0.55378379, 6.42380595, 0.05401805, 0.16009754])

In [21]:
mul

array([0.03105155, 0.40484198, 0.22095485, 0.61889896, 0.31174162,
       0.1041097 , 0.01414679, 0.09233395, 0.034435  , 0.07537014])

In [22]:
dot

1.9078845249645118

In [24]:
#statistical functions

sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [25]:
sqrt

5.0

In [26]:
ab

2

In [27]:
power

128

In [28]:
log

3.2188758248682006

In [29]:
exp

array([ 7.3890561 , 20.08553692])

In [30]:
mins

0.04312901321406193

In [31]:
maxs

0.8946647893819496

In [32]:
#data manipulation


In [33]:
data

array([[[0.6226004 , 0.63728812, 0.99969225, 0.23295686],
        [0.42812099, 0.12910182, 0.91996601, 0.80012917],
        [0.93121527, 0.00516949, 0.4965076 , 0.20494078]],

       [[0.13764665, 0.50697818, 0.87629618, 0.56344218],
        [0.21418864, 0.78503022, 0.67751233, 0.28541962],
        [0.08911955, 0.20271771, 0.00100353, 0.74606217]]])

In [34]:
data[0][0][0] = 700

In [35]:
data

array([[[7.00000000e+02, 6.37288121e-01, 9.99692248e-01, 2.32956863e-01],
        [4.28120991e-01, 1.29101819e-01, 9.19966006e-01, 8.00129173e-01],
        [9.31215265e-01, 5.16948793e-03, 4.96507602e-01, 2.04940779e-01]],

       [[1.37646651e-01, 5.06978176e-01, 8.76296182e-01, 5.63442182e-01],
        [2.14188644e-01, 7.85030218e-01, 6.77512330e-01, 2.85419617e-01],
        [8.91195479e-02, 2.02717715e-01, 1.00353037e-03, 7.46062167e-01]]])

In [37]:
data.sort()
data

array([[[2.32956863e-01, 6.37288121e-01, 9.99692248e-01, 7.00000000e+02],
        [1.29101819e-01, 4.28120991e-01, 8.00129173e-01, 9.19966006e-01],
        [5.16948793e-03, 2.04940779e-01, 4.96507602e-01, 9.31215265e-01]],

       [[1.37646651e-01, 5.06978176e-01, 5.63442182e-01, 8.76296182e-01],
        [2.14188644e-01, 2.85419617e-01, 6.77512330e-01, 7.85030218e-01],
        [1.00353037e-03, 8.91195479e-02, 2.02717715e-01, 7.46062167e-01]]])

In [39]:
print(data.shape)

(2, 3, 4)


In [41]:
data = data.reshape((2,2,6))

In [42]:
data.shape

(2, 2, 6)

In [43]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [44]:
zeros.shape

(2, 2, 2)

In [45]:
zeros1 = np.append(zeros, [3,4])

In [46]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [47]:
zeros1

array([0., 0., 0., 0., 0., 0., 0., 0., 3., 4.])

In [48]:
zeros1 = np.insert(zeros1,2,1)

In [49]:
zeros1

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 3., 4.])

In [51]:
#Delete 


In [54]:
data

array([[[2.32956863e-01, 6.37288121e-01, 9.99692248e-01, 7.00000000e+02,
         1.29101819e-01, 4.28120991e-01],
        [8.00129173e-01, 9.19966006e-01, 5.16948793e-03, 2.04940779e-01,
         4.96507602e-01, 9.31215265e-01]],

       [[1.37646651e-01, 5.06978176e-01, 5.63442182e-01, 8.76296182e-01,
         2.14188644e-01, 2.85419617e-01],
        [6.77512330e-01, 7.85030218e-01, 1.00353037e-03, 8.91195479e-02,
         2.02717715e-01, 7.46062167e-01]]])

In [55]:
np.delete(data, 0 , axis=1)

array([[[0.80012917, 0.91996601, 0.00516949, 0.20494078, 0.4965076 ,
         0.93121527]],

       [[0.67751233, 0.78503022, 0.00100353, 0.08911955, 0.20271771,
         0.74606217]]])

In [ ]:
np.save("new array1",data)